# Languages
languages:
   Java: true

# Ignore files that are not relevant for the check
exclude_paths:
    - out/*
    - target/*

# Enables useful engines
engines:
  # Checks for left TODO marks
  fixme:
    enabled: true
  # Another Java code style checking. Testable
  pmd:
    enabled: true
    channel: "beta"
  # Java Code Style checking
  checkstyle:
    enabled: true
    channel: "beta"
    checks:
      # We can't check line length here, cause 100 is too short and we don't have
      # a configuration xml file. Codacy checks that alone then.
      com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
        enabled: false
      # Checking for order of customs does not work, it misses a lot of libraries.
      # So we just remove that check.
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false
      # It should be allowed to declare multiple variables at once, if each is in a new line.
      com.puppycrawl.tools.checkstyle.checks.coding.MultipleVariableDeclarationsCheck:
        enabled: false

ratings:
  paths:
  - "**.java"
