# Languages
languages:
   Java: true

# Ignore files that are not relevant for the check
exclude_paths:
    - out/*
    - target/*
    - checkstyle.xml

# Enables useful engines
engines:
  # Checks for left TODO marks
  fixme:
    enabled: true
  # Another Java code style checking. Testable
  pmd:
    enabled: true
    channel: "beta"
  # Java Code Style checking
  checkstyle:
    enabled: true
    channel: "beta"
    config: 'checkstyle.xml'

ratings:
  paths:
  - "**.java"
